{% set version = "1.2.0" %}

package:
  name: smt
  version: {{ version }}

source:
  fn: smt-{{ version }}.tar.gz
  url: https://github.com/SMTorg/smt/archive/v{{ version }}.tar.gz
  sha256: 133928acf70d06c0c9e51e770a34bdf0794a41f36e5344cadd46b4d16a3b775e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [py35]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - setuptools
    - cython
    - python
    - numpy


  run:
    - python
    - packaging
    - pydoe2
    - scikit-learn
    - {{ pin_compatible('numpy') }}
    - scipy
    - matplotlib-base

test:
  imports:
    - smt
    - smt.surrogate_models
    - smt.problems
    - smt.sampling_methods
    - smt.utils

about:
  home: https://github.com/SMTorg/smt
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: surrogate model toolbox

extra:
  recipe-maintainers:
    - relf
