{% set version = "0.3.2" %}

package:
  name: smt
  version: {{ version }}

source:
  fn: smt-{{ version }}.tar.gz
  url: https://github.com/SMTorg/smt/archive/v{{ version }}.tar.gz
  sha256: 1c390a9e27c5cb4edfd265ce128d78e6a3f3743b2bcd9214c003b88199f89f2d

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: true  # [py35]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - setuptools
    - cython
    - python
    - numpy


  run:
    - python
    - pydoe2
    - scikit-learn
    - {{ pin_compatible('numpy') }}
    - six
    - matplotlib

test:
  imports:
    - smt
    - smt.surrogate_models
    - smt.problems
    - smt.sampling_methods
    - smt.utils

about:
  home: https://github.com/SMTorg/smt
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: surrogate model toolbox

extra:
  recipe-maintainers:
    - jschueller
