{% set version = "0.2" %}

package:
  name: smt
  version: {{ version }}

source:
  fn: smt-{{ version }}.tar.gz
  url: https://github.com/SMTorg/smt/archive/v{{ version }}.tar.gz
  sha256: 662616ee8112df5fa7e5cceb8e8e339a273bf5d39e668319768d70077484fcd4
  patches:
    # https://github.com/SMTorg/smt/pull/67
    - setuptools.patch
    # https://github.com/SMTorg/smt/pull/70
    - cython.patch
    # https://github.com/SMTorg/smt/pull/71
    - cxx11.patch
    # https://github.com/SMTorg/smt/pull/72
    - nominmax.patch

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - toolchain
    - setuptools
    - cython
    - python
    - numpy 1.9.*  # [not (win and py36)]
    - numpy 1.11.*  # [win and py36]

  run:
    - python
    - pydoe
    - scikit-learn
    - numpy >=1.9  # [not (win and py36)]
    - numpy >=1.11  # [win and py36]
    - six

test:
  imports:
    - smt
    - smt.methods
    - smt.problems
    - smt.sampling

about:
  home: https://github.com/SMTorg/smt
  license: BSD 3-Clause
  # https://github.com/SMTorg/smt/issues/68
  #license_file: COPYING
  summary: surrogate model toolbox

extra:
  recipe-maintainers:
    - jschueller
