{% set version = "0.1" %}

package:
  name: smt
  version: {{ version }}

source:
  fn: smt-{{ version }}.tar.gz
  url: https://github.com/SMTorg/smt/archive/v{{ version }}.tar.gz
  sha256: 784d9f482cdc2e0eadad64da600e27ae5390ccb09671889bdd659f4bc0aa6908
  patches:
    # https://github.com/SMTorg/smt/pull/67
    - setuptools.patch
    # https://github.com/SMTorg/smt/pull/70
    - cython.patch
    # https://github.com/SMTorg/smt/pull/71
    - cxx11.patch
    # https://github.com/SMTorg/smt/pull/72
    - nominmax.patch

build:
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - setuptools
    - cython
    - python
    - numpy        # [not (win and py36)]
    - numpy         # [win and py36]

  run:
    - python
    - pydoe
    - scikit-learn
    - {{ pin_compatible('numpy') }}   # [not (win and py36)]
    - {{ pin_compatible('numpy') }}   # [win and py36]
    - six

test:
  imports:
    - smt
    - smt.methods
    - smt.problems
    - smt.sampling

about:
  home: https://github.com/SMTorg/smt
  license: BSD 3-Clause
  # https://github.com/SMTorg/smt/issues/68
  #license_file: COPYING
  summary: surrogate model toolbox

extra:
  recipe-maintainers:
    - jschueller
