{% set version = "2.9.1" %}

package:
  name: smt
  version: {{ version }}

source:
  fn: smt-{{ version }}.tar.gz
  url: https://github.com/SMTorg/smt/archive/v{{ version }}.tar.gz
  sha256: 2a2752866000bfda442aa8a2fd1061d86c3d4ec1aa2ed1e229b83b82c111dde8

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cross-python_{{ target_platform }}    # [build_platform != target_platform]
    - python                                # [build_platform != target_platform]
    - cython                                # [build_platform != target_platform]
    - numpy                                 # [build_platform != target_platform]    
  host:
    - pip
    - setuptools
    - cython
    - python
    - numpy
  run:
    - python
    - numpy
    - pydoe3
    - scikit-learn
    - jenn

test:
  imports:
    - smt
    - smt.surrogate_models
    - smt.kernels
    - smt.problems
    - smt.sampling_methods
    - smt.applications

about:
  home: https://github.com/SMTorg/smt
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: surrogate model toolbox

extra:
  recipe-maintainers:
    - relf
