{% set version = "2.2.1" %}

package:
  name: smt
  version: {{ version }}

source:
  fn: smt-{{ version }}.tar.gz
  url: https://github.com/SMTorg/smt/archive/v{{ version }}.tar.gz
  sha256: c40baed6cb120d4f51447587326a4df277284522988911aa3c87c9040d28cf74

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - setuptools
    - cython
    - python
    - numpy


  run:
    - python
    - pydoe3
    - scikit-learn
    - {{ pin_compatible('numpy') }}
    - scipy
    - matplotlib-base

test:
  imports:
    - smt
    - smt.surrogate_models
    - smt.problems
    - smt.sampling_methods
    - smt.utils

about:
  home: https://github.com/SMTorg/smt
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: surrogate model toolbox

extra:
  recipe-maintainers:
    - relf
