{% set version = "2.8.0" %}

package:
  name: smt
  version: {{ version }}

source:
  fn: smt-{{ version }}.tar.gz
  url: https://github.com/SMTorg/smt/archive/v{{ version }}.tar.gz
  sha256: 784d9f482cdc2e0eadad64da600e27ae5390ccb09671889bdd659f4bc0aa6908
  patches:
    # https://github.com/SMTorg/smt/pull/67
    - setuptools.patch
    # https://github.com/SMTorg/smt/pull/70
    - cython.patch
    # https://github.com/SMTorg/smt/pull/71
    - cxx11.patch
    # https://github.com/SMTorg/smt/pull/72
    - nominmax.patch

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - toolchain
    - setuptools
    - cython
    - python
    - numpy
  run:
    - python
    - numpy
    - pydoe3
    - scikit-learn
    - jenn

test:
  imports:
    - smt
    - smt.surrogate_models
    - smt.kernels
    - smt.problems
    - smt.sampling_methods
    - smt.applications

about:
  home: https://github.com/SMTorg/smt
  license: BSD-3-Clause
  summary: surrogate model toolbox

extra:
  recipe-maintainers:
    - jschueller
    - relf
