{% set version = "0.5.2" %}

package:
  name: smt
  version: {{ version }}

source:
  fn: smt-{{ version }}.tar.gz
  url: https://github.com/SMTorg/smt/archive/v{{ version }}.tar.gz
  sha256: 4852c0079bc91af8031e48cbf62d79ee17543a6bc0fe68a0723f3112ce82e887

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [py35]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - setuptools
    - cython
    - python
    - numpy


  run:
    - python
    - pydoe2
    - scikit-learn
    - {{ pin_compatible('numpy') }}
    - six
    - matplotlib-base

test:
  imports:
    - smt
    - smt.surrogate_models
    - smt.problems
    - smt.sampling_methods
    - smt.utils

about:
  home: https://github.com/SMTorg/smt
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: surrogate model toolbox

extra:
  recipe-maintainers:
    - relf
