travis:
  secure:
    BINSTAR_TOKEN: i6naQ/ecUsnYvgQjkrn+mU5jWLtpJtkgcAJKCmUdI2DuL+BJsstjp2KncRaGyirogBLN+9am8VnQPzB2O1tmPsz0oM1yIA0i0oiDfzA5TTTxRJ4D6TkAnnMP7V1IU4CfK4qfWxOxgpj+DxJEfSfEhmtOPid4XryKQqM1q/+NtMHghPDTaIUvyPVvmTMF9IsPTg1Z92vrcV+Vtd9IzqXsmP2stEDLKdzcpcQXQu85BkQA4ZuWCZmOvYECLU9cbJ67uXyf934uhnbBQRRUzDlmPdxHUUQ9wpWxoxJgRCy+Ep3WHOVQV/NpzkLtKmBcweZJboSVRSDUlfsSdl4MAoevLVbiSa4ZTevvBjFuPUZIZP5JXifFIrcpkvmdpi1OOcTXw00SAzNOEmTN8PeF6fP+JG20vc0GL7Xs6cQhzI7rQEWPnf+399t0SsqkL1pRIrRpc1C3zA9J1CaX8oXC/T1mNARDfTUYmPEv6oEIIOklZy3jnje33dkd5KUj/ZB3I8wG7covmpiVm69wRIILVSmZPoEp1xzk/J/f/6b2bH/vEFOtEOs+wO0gSAIYkVlC/7Mc1gLkr9t9yE89tXquIsEpoean4dDd2E7Ss3ApM6jShc0LjgR1th7v/4DWOfkDAe/YA4D21z7hEYkE0OVOqTuv2QFkWs4DCLe9J0kwA/wI8Co=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
