travis:
  secure:
    BINSTAR_TOKEN: LPZIuyVkQRAcWQVMgcCgm1ucTezYFxmze0zsIlKULrdKTxP1NbT08aCBkkP6onOVnZUoCt/JFpodCnghgXmX8titTvzHt+GuxprqeNrtyFdnTz1neyvFJ+eab+PiZhbKjV5dcVc2UuTytq8s0rB8XpsdX1NgGJYhhLy1xXjUHMzrSfQxBN6SKAv6a3POMVQgsEFXJ5d18F92NmqHr+D4PLdkxwluqRR8TnVzjdLKz76ZqmTJ9u3Y3SbM0AyvpwYZ9tH8sErVXqtfpIylR22zR6ViJVHnk0JdTxg68e569XcM0CmSIHVfLubEzcI1Wwv6q8Pc36jCBTxDtft7+pnvZHc5XWLOfbxRUndec2MSBraPSwqJBRiFIdz63mnF2scbw7e93uogXS4W6t13ag6j+MR7EgO2B0NgsAZH+HU6UXsyC3898PaY4iGH3n2IdzYVxI6FLEKHEfSah1n1F1LE0issklAEp8z8W/Jm9DK3YeVNt/ociP0mZP9lR8BT07lFq2d6+hTufMg7Qfoc1L1UPRop0jrLL62hFP5GmUVgia5YeCBKujLfCOoi6rcjfMoTPjigqbiq132nS2yA4Nm1dldQvP8MJAVv96+O0/q2zsTUw4r5uoXsxDIrQjiYyUJZsvDKYDmOC5bhKdCJ67DCa+Q0NOR61AXReTqyy5AJJ0Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
